// src/views/PositionCalculator.vue
<template>
  <h1>OOTP Position Calculator</h1>
  <div id="overview">
    <p>By entering a player's defensive ratings, the position calculator will tell you how good they could be at any position.</p>
    <p>Height must be entered to generate a 1B rating. Left-handed throwers cannot play C, 2B, 3B, or SS.</p>
  </div>
  <form @submit="submit($event)">
  <div class="row-flex row-container">
    <div class="column-split">
      <div class="row-flex checks">
        <!--
        <checkbox ref="checkSaveEntry" @click="clickSaveEntry()" :table="true"/>
        <label>Save Entry</label>
        -->
        <checkbox ref="checkCentimetres" @click="clickCentimetres()" :table="true"/>
        <label>Use Centimetres</label>
      </div>
      <table class="table-projections table-input table-vertical">
        <colgroup>
          <col class="bordered">
          <col>
        </colgroup>
        <tr>
          <th>Ratings Scale</th>
          <td><ratings-scale ref="scale" /></td>
        </tr>
        <tr :class="{ hidden: !saveEntry }">
          <th>
            <div class="collapsible">Name</div>
          </th>
          <td>
            <div class="collapsible"><input type="text" id="name" v-model="player.name"></div>
          </td>
        </tr>
        <tr>
          <th>Height</th>
          <td v-if="centimetres"><input type="number" v-model="htCm" placeholder="centimetres"></td>
          <td v-if="!centimetres">
            <div class="cell-double">
              <div><input type="number" v-model="htFt" placeholder="feet"></div>
              <div><input type="number" v-model="htIn" placeholder="inches"></div>
            </div>
          </td>
        </tr>
        <tr><th class="empty"></th></tr>
        <tr>
          <th>Catcher Abil</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.catcherAbil"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Catcher Arm</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.catcherArm"></div>
            </div>
          </td>
        </tr>
        <tr><th class="empty"></th></tr>
        <tr>
          <th>Infield Rng</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.infieldRng"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Infield Err</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.infieldErr"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Infield Arm</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.infieldArm"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Turn DP</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.turnDP"></div>
            </div>
          </td>
        </tr>
        <tr><th class="empty"></th></tr>
        <tr>
          <th>Outfield Rng</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.outfieldRng"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Outfield Err</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.outfieldErr"></div>
            </div>
          </td>
        </tr>
        <tr>
          <th>Outfield Arm</th>
          <td>
            <div class="cell-double">
              <div><input type="number" v-model="player.outfieldArm"></div>
            </div>
          </td>
        </tr>
      </table>
      <div class="row-flex">
      <button class="button-submit" type="submit"> {{ editing ? 'Save' : 'Submit' }}</button>
      <button class="button-clear" type="button" @click="clear()" v-if="!editing">Clear</button>
      <button class="button-clear" type="button" @click="deletePlayer()" v-if="editing">Delete</button>
    </div>
    <p class="error">{{error}}</p>
    </div>
    <div class="column-split">
      <div class="row-flex checks">&nbsp;</div>
      <table class="table-projections" id="table-output">
        <thead>
          <tr>
            <th>Position</th>
            <th>Rating</th>
            <th>WAR</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="(position, index) in positions">
            <td>{{position}}</td>
            <td :style="`color: ${getColor(index)};`">{{getRating(index)}}</td>
            <td>{{getWAR(index)}}</td>
          </tr>
        </tbody>
      </table>
      <div class="notes">
        <h3>Notes</h3>
        <p><strong>Height</strong> only affects First Base rating.</p>
        <p><strong>Lefties</strong> will not generate ratings at C, 2B, 3B, or SS.</p>
        <p><strong>Rating</strong> is the player's maximum possible defensive rating for the given position.</p>
        <p><strong>WAR</strong> is the player's <i>estimated</i> full-season defensive WAR for the given position.</p>
      </div>
    </div>
  </div>
</form>

</template>

<script>
import RatingsScale from '@/components/Projections/RatingsScale.vue';
import Checkbox from '@/components/Checkbox.vue';
import { Fielder } from '../data-classes';

export default {
  name: 'PositionCalculator',
  components: { RatingsScale, Checkbox },
  data() {
    return {
      centimetres: false,
      saveEntry: false,
      htFt: '',
      htIn: '',
      htCm: '',
      player: { name: '', height: '' },
      display: [],
      players: [],
      error: '\xa0',
      editing: false,
      scale: {selected: '20 to 80'},
      positions: ['Catcher', 'First Base', 'Second Base', 'Third Base', 'Shortstop', 'Left Field', 'Center Field', 'Right Field']
    }
  },
  created() {
    document.title = 'Position Calculator | OOTP Calculator';
    let players = localStorage.getItem('fielding');
    if (players && players != 'undefined') {
      this.players = JSON.parse(players);
    }
  },
  mounted() {
    this.scale = this.$refs.scale;
    if (localStorage.getItem('use-centimetres') == 'true') {
      this.centimetres = true;
      this.$refs.checkCentimetres.select();
    }
    /*
    if (localStorage.getItem('save-entry') == 'true') {
      this.saveEntry = true;
      this.$refs.checkSaveEntry.select();
    }
    */
  },
  methods: {
    submit(event) {
      event.preventDefault();
      try {
        if ((this.htFt || this.htFt === 0) && (this.htIn || this.htIn === 0)) {
          this.player.height = 2.54 * (12 * this.htFt + +this.htIn);
        } else if (this.htCm) {
          this.player.height = +this.htCm;
        }
        let result = new Fielder(this.scale.selected, this.player, this.saveEntry);
        this.display = result.getDisplay(this.scale.selected);
        // this.clear();
        this.error = '\xa0';
        this.$analytics.logEvent(this.$instance, 'calculate-position');
      } catch (error) {
        this.error = '\xa0';
        setTimeout(() => this.error = error, 100);
      }
    },

    clear() {
      this.htFt = '';
      this.htIn = '';
      this.htCm = '';
      this.player = { name: '', height: '' };
      this.display = [];
      this.error = '\xa0';
    },

    clickCentimetres() {
      this.centimetres = !this.centimetres;
      localStorage.setItem('use-centimetres', this.centimetres.toString());
      this.$analytics.logEvent(this.$instance, `change-units`);
      let units = this.centimetres ? 'cm' : 'in';
      this.$analytics.logEvent(this.$instance, `units-${units}`);
    },

    clickSaveEntry() {
      this.saveEntry = !this.saveEntry;
      localStorage.setItem('save-entry', this.saveEntry.toString());
    },

    getRating(index) {
      let min = +(this.scale.selected.split(' to ')[0]);
      let display = this.display[index];
      if (display) {
        if (display.rating == 0) {
          return '-'
        }
        return Math.max(display.grade, min);
      }
      return '-';
    },

    getWAR(index) {
      let display = this.display[index];
      if (display) {
        if (display.rating == 0) {
          return '-'
        }
        return display.war.toFixed(1);
      }
      return '-';
    },

    getColor(index) {
      let display = this.display[index];
      if (display) {
        if (display.rating == 0) {
          return '-'
        }
        return display.color;
      }
      return '-';
    }
  }
}
</script>

<style>

.notes h3 {
  font-size: 1.25rem;
}

.notes p {
  font-size: .75rem;
  margin-bottom: 0;
  margin-top: .5rem;
}


</style>

<style scoped>

label {
  margin-top: -2px;
}

.notes {
  text-align: left;
  margin: auto;
  padding: 32px;
  max-width: 25rem;
}

td {
  width: 10rem;
}

.cell-double {
  display: flex;
}

.cell-double div {
  width: 50%;
}

.cell-double div input {
  width: 100% !important;
}

.collapsible {
  transition: all .2s;
  transition-property: max-height, opacity;
  max-height: 2rem;
  overflow: hidden;
}

.hidden .collapsible {
  max-height: 0;
  opacity: 0;
}

.hidden td, .hidden th {
  padding: 0;
  margin: 0;
}


th.empty {
  padding: 8px;
}

.column-split {
  width: 50%;
  padding: 0.5rem;
}

@media (max-width: 40rem) {
  .column-split {
    width: 100%; 
  }
  .row-flex.row-container {
    flex-direction: column;
  }
}

#table-output {
  max-width: 25rem;
  margin: auto;
}

#table-output td {
  padding: 5px 10px;
}

#table-output tr {
  border-bottom: 1px solid var(--color-transparent);
}

/*
#table-output tbody tr {
  background-color: rgba(0, 20, 41, 0.8);
}

#table-output tr:nth-child(even) {
  background-color: rgba(10, 30, 62, 0.7);
}
*/

</style>

// src/app/position-calculator/position-calculator.component.ts
import { ThrowStmt } from '@angular/compiler';
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-position-calculator',
  templateUrl: './position-calculator.component.html',
  styleUrls: ['./position-calculator.component.css']
})
export class PositionCalculatorComponent implements OnInit {

    scale: string;  // Ratings scale; '20 to 80', '1 to 5', etc.
    feet: number;  
    inches: number; 
    errorIn: boolean;  // Error in inches
    centimeters: number;
    errorCm: boolean;  // Error in centimeters
    useCm: boolean;  // Whether or not centimeters are used
    useIn: boolean;  // Whether or not inches are used
    lefty: boolean;  // Whether or not the player throws left
    skills: number[];  // Defensive skills
    errorRange: boolean;  // Outside of range
    errorInterval: boolean;  // Not a multiple of 5 (20-80)
    errorGroup: boolean;
    errorCatcher: boolean;  // Need 1 full group
    errorInfield: boolean;
    errorOutfield: boolean; 
    positions: string[];  // List of positions
    ratings: string[];  // Ratings corresponding with positions
    colors: string[];  // Colors corresponding with ratings
    wars: string[];  // WAR values corresponding with ratings

    constructor() { 
        this.scale = "20 to 80";
        this.useCm = false;
        this.useIn = true;
        this.lefty = false;
        this.errorIn = false;
        this.errorCm = false;
        this.skills = [null, null, null, null, null, null, null, null, null];
        this.errorRange = false;
        this.errorInterval = false;
        this.errorGroup = false;
        this.errorCatcher = false;
        this.errorInfield = false;
        this.errorOutfield = false;
        this.positions = ["Catcher", "First Base", "Second Base", "Third Base", "Shortstop", "Left Field", "Center Field", "Right Field"];
        this.ratings = ["-", "-", "-", "-", "-", "-", "-", "-"];
        this.colors = ["#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff"];
        this.wars = ["-", "-", "-", "-", "-", "-", "-", "-"];
    }

    ngOnInit(): void {
    }

    onChange(): void {
        this.useCm = !this.useCm;
        this.useIn = !this.useIn;

        if (this.useCm && this.inches != null && this.feet != null) {
            this.centimeters = Math.round(2.54 * (12 * this.feet + this.inches));
        } else if (this.centimeters != null) {
            var inches = Math.round(this.centimeters / 2.54);
            this.feet = Math.floor(inches / 12);
            this.inches = inches % 12;
        } else {
            this.inches = null;
            this.feet = null;
            this.centimeters = null;
        }

        this.errorCm = false;
        this.errorIn = false;
    }

    onSubmit(event: Event): void {
        event.preventDefault();
        var valid = this.validate();
        if (valid) {
            this.calculatePositions();
        }
    }

    onClear(event : Event): void {
        event.preventDefault();
        this.feet = null;
        this.inches = null;
        this.centimeters = null;
        this.lefty = false;
        this.errorIn = false;
        this.errorCm = false;
        this.skills = [null, null, null, null, null, null, null, null, null];
        this.errorRange = false;
        this.errorInterval = false;
        this.errorGroup = false;
        this.errorCatcher = false;
        this.errorInfield = false;
        this.errorOutfield = false;
        this.positions = ["Catcher", "First Base", "Second Base", "Third Base", "Shortstop", "Left Field", "Center Field", "Right Field"];
        this.ratings = ["-", "-", "-", "-", "-", "-", "-", "-"];
        this.colors = ["#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff"];
        this.wars = ["-", "-", "-", "-", "-", "-", "-", "-"];
    }

    validate(): boolean {
        // Validate height
        if (this.useIn) {
            if (this.feet < 0 || this.feet > 11 || this.inches < 0 || this.inches > 11) {
                this.errorIn = true;
            } else {
                this.errorIn = false;
            }
        } else if (this.centimeters < 0) {
            this.errorCm = true;
        } else {
            this.errorCm = false;
        }
        // Validate range & intervals
        var skill;
        var split = this.scale.split(" ");
        var min = Number(split[0]);
        var max = Number(split[2]);
        var converted;
        var half;

        if (min == 20) {
            half = 2.5;
        } else {
            half = 0.5;
        }

        this.errorRange = false;
        this.errorInterval = false;

        for (var i = 0; i < this.skills.length; ++i) {
            skill = this.skills[i];
            if (skill != null) {
                converted = (skill - min - half - 1) * (200 / (max - min));
                console.log(i + ": " + converted);
                if (skill < min || converted > 250) {
                    this.errorRange = true;
                    break;
                }
            } else if (this.scale == "20 to 80" && (skill % 5 != 0)) {
                this.errorInterval = true;
                break;
            }
        }

        this.errorCatcher = true;
        this.errorInfield = true;
        this.errorOutfield = true;

        if (this.skills[0] != null && this.skills[1] != null) {
            this.errorCatcher = false;
        } 
        
        if (this.skills[2] != null && this.skills[3] != null && this.skills[4] != null && this.skills[5] != null) {
            this.errorInfield = false;
        } 
        
        if (this.skills[6] != null && this.skills[7] != null && this.skills[8] != null) {
            this.errorOutfield = false;
        }

        if (!this.errorRange && !this.errorInterval && (this.errorCatcher && this.errorInfield && this.errorOutfield)) {
            this.errorGroup = true;
        } else {
            this.errorGroup = false;
        }

        return !(this.errorCm || this.errorIn || this.errorRange || this.errorInterval || this.errorGroup);
    }

    calculatePositions(): void {
        // Initialize
        this.ratings = ["-", "-", "-", "-", "-", "-", "-", "-"];
        this.colors = ["#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff", "#ffffff"];
        this.wars = ["-", "-", "-", "-", "-", "-", "-", "-"];

        // Get scale max/min
        var split = this.scale.split(" ");
        var min = Number(split[0]);
        var max = Number(split[2]);

        // Convert to 1-250
        var half;
        if (min == 20) {
            half = 5 / 2;
        } else {
            half = 1 / 2;
        }

        var converted: number[] = [null, null, null, null, null, null, null, null, null];
        var grade;
        var num;
        for (var i = 0; i < converted.length; ++i) {
            if (this.skills[i] == null) {
                continue;
            }
            grade = this.skills[i];
            num = Math.ceil(((grade + half) - min) * 200 / (max - min) - 1);
            if (num > 250) {
                converted[i] = 250;
            } else {
                converted[i] = num;
            }
        }

        var ratings = [0, 0, 0, 0, 0, 0, 0, 0];
        var abil;
        var arm;
        var range;
        var error;
        var turn;

        // Calculate positional value, shoutout to u/bvimarlins
        // Calculate catcher
        if (!this.errorCatcher) {
            abil = (converted[0] - 125) / 25 * 19.5;
            arm = (converted[1] - 125) / 25 * 19.5;
            ratings[0] = abil + arm + 133;
        }

        // Calculate 1B
        var height;
        if (this.useIn) {
            height = Math.round(30.48 * this.feet + 2.54 * this.inches);
        } else {
            height = this.centimeters;
        }

        if (height > 0 && !this.errorInfield) {
            if (height > 215) {
                height = 215;
            }
            range;
            error;
            if (converted[2] < 90) {
                range = converted[2] / 3;
            } else {
                range = 30 + (converted[2] - 90) * 2 / 25;
            }

            if (converted[3] < 90) {
                error = converted[3] / 5;
            } else {
                error = 18 + (converted[3] - 90) / 25;
            }
            arm = converted[4] / 70;
            turn = converted[5] / 70;
            var hfac = 1 + (height - 155) / 15;
            ratings[1] = hfac * (range + error + arm + turn);
        }

        // Calculate rest of IF
        if (!this.errorInfield && !this.lefty) {
            range = (converted[2] - 125) / 25 * 21.5;
            error = (converted[3] - 125) / 25 * 8.25;
            arm = (converted[4] - 125) / 25 * 1.5;
            turn = (converted[5] - 125) / 25 * 9;
            ratings[2] = range + error + arm + turn + 129;
            range = (converted[2] - 125) / 25 * 13;
            error = (converted[3] - 125) / 25 * 7.5;
            arm = (converted[4] - 125) / 25 * 17;
            turn = (converted[5] - 125) / 25 * 3.25;
            ratings[3] = range + error + arm + turn + 113.5;
            range = (converted[2] - 125) / 25 * 25.5;
            error = (converted[3] - 125) / 25 * 7.5;
            arm = (converted[4] - 125) / 25 * 2;
            turn = (converted[5] - 125) / 25 * 8;
            ratings[4] = range + error + arm + turn + 93.75;
        }

        // Calculate OF
        if (!this.errorOutfield) {
            range = (converted[6] - 125) / 25 * 29.5;
            error = (converted[7] - 125) / 25 * 4;
            arm = (converted[8] - 125) / 25 * 5.75;
            ratings[5] = range + error + arm + 149;
            range = (converted[6] - 125) / 25 * 43;
            error = (converted[7] - 125) / 25 * 3.5;
            arm = (converted[8] - 125) / 25 * 1.75;
            ratings[6] = range + error + arm + 78;
            range = (converted[6] - 125) / 25 * 25.5;
            error = (converted[7] - 125) / 25 * 4;
            arm = (converted[8] - 125) / 25 * 11;
            ratings[7] = range + error + arm + 129;
        }

        // Convert back, get colors and WARs
        var slopes = [0.003, 0.009, 0.018, 0.015, 0.024, 0.009, 0.015, 0.009];
        var intercepts = [1.1, -1.75, -1.5, -1.05, -1.8, -1.3, -1.15, -1.25];
        var rating;
        var grade;
        var war;
        for (var i = 0; i < ratings.length; ++i) {
            rating = ratings[i];
            grade = (rating * (max - min) / 200) + min;
            if (min == 20) {
                grade = Math.round(grade / 5) * 5;
            } else {
                grade = Math.round(grade);
            }
            if (grade > min) {
                this.ratings[i] = String(grade);
                war = Math.round((slopes[i] * rating + intercepts[i]) * 10) / 10;
                this.wars[i] = war.toFixed(1);
                if (rating < 9)
                    this.colors[i] = "#A40000";
                else if (rating < 25)
                    this.colors[i] = "#CB0000";
                else if (rating < 42)
                    this.colors[i] = "#FD0000";
                else if (rating < 59)
                    this.colors[i] = "#FD6A00";
                else if (rating < 75)
                    this.colors[i] = "#FDBC00";
                else if (rating < 92)
                    this.colors[i] = "#EBDF08";
                else if (rating < 109)
                    this.colors[i] = "#BBD500";
                else if (rating < 125)
                    this.colors[i] = "#56D100";
                else if (rating < 142)
                    this.colors[i] = "#57CF1F";
                else if (rating < 159)
                    this.colors[i] = "#76D086";
                else if (rating < 179)
                    this.colors[i] = "#00C4C6";
                else if (rating < 192)
                    this.colors[i] = "#00C3E5";
                else
                    this.colors[i] = "#0095FB";
            } else if (rating != 0) {
                this.ratings[i] = String(min);
                this.colors[i] = "#A40000";
            }
        }
    }
}

<div class="container-fluid" style="padding-bottom: 40px">
    <h1 class="title">OOTP POSITION CALCULATOR</h1><hr>
    <p>Ever wondered how good your players might be if they changed positions? Well wonder no longer! By simply entering a player's defensive ratings, this calculator will tell you exactly how good they could be at any position.</p>
    <p>If you don't care how a player performs at a certain position (e.g. don't care about infield ratings), just leave those fields blank. Make sure to fill out the player's height if you want a first base rating. Be warned - left-handed throwers can't accrue experience at 2B, 3B or SS.</p>
    <hr>
    <div class="row">
        <div class="col-md-6">
            <h2>ENTER PLAYER RATINGS</h2>
            <hr>
            <form id="form-position">
                <div class="form-group row">
                    <label class="col-lg-5" for="scale">Ratings Scale</label>
                    <select class="form-control col-lg-7" name="scale" [(ngModel)]="this.scale" (change)="onClear($event)">
                        <option>1 to 5</option>
                        <option>2 to 8</option>
                        <option>1 to 10</option>
                        <option>1 to 20</option>
                        <option selected>20 to 80</option>
                        <option>1 to 100</option>
                    </select>
                </div>
                <div class="form-group row topless" id="height-inches" *ngIf="this.useIn">
                    <label class="col-lg-5" for="feet">Height (ft-in)</label>
                    <input class="form-control col-lg-3" type="number" placeholder="feet" id="feet" name="feet" [(ngModel)]="this.feet"/>
                    <div class="col-lg-1"></div>
                    <input class="form-control col-lg-3" type="number" placeholder="inches" name="inches" [(ngModel)]="this.inches"/>
                </div>
                <div class="row">
                    <div *ngIf="this.errorIn" class="col-11 error">Height values must be between 0 and 11!</div>
                </div>
                <div class="form-group row topless" id="height-centimeters" *ngIf="this.useCm">
                    <label class="col-lg-5" for="centimeters">Height (cm)</label>
                    <input class="form-control col-lg-7" type="number" placeholder="centimeters" id="centimeters" name="centimeters" [(ngModel)]="this.centimeters"/>
                </div>
                <div class="row" *ngIf="this.errorCm">
                    <div class="col-11 error">Height value cannot be negative!</div>
                </div>
                <div class="row">
                    <div class="col-lg-5"></div>
                    <div class="col-lg-3">
                        <input class="form-check-input check-ootp" type="checkbox" id="unit-check" (click)="onChange()"/>
                        <label class="form-check-label" for="unit-check">use cm</label>
                    </div>
                    <div class="col-lg-4">
                        <input class="form-check-input check-ootp" type="checkbox" name="lefty" [(ngModel)]="this.lefty"/>
                        <label class="form-check-label" for="lefty">throws left</label>
                    </div>
                </div>
                <br>
                <div class="form-group row">
                    <label class="col-lg-5" for="cabl">Catcher Ability</label>
                    <input class="form-control col-lg-3" type="number" name="cabl" [(ngModel)]="this.skills[0]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="carm">Catcher Arm</label>
                    <input class="form-control col-lg-3" type="number" name="carm" [(ngModel)]="this.skills[1]"/>
                </div>
                <br>
                <div class="form-group row">
                    <label class="col-lg-5" for="irng">Infield Range</label>
                    <input class="form-control col-lg-3" type="number" name="irng" [(ngModel)]="this.skills[2]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="ierr">Infield Error</label>
                    <input class="form-control col-lg-3" type="number" name="ierr" [(ngModel)]="this.skills[3]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="iarm">Infield Arm</label>
                    <input class="form-control col-lg-3" type="number" name="iarm" [(ngModel)]="this.skills[4]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="turn">Turn DP</label>
                    <input class="form-control col-lg-3" type="number" name="turn" [(ngModel)]="this.skills[5]"/>
                </div>
                <br>
                <div class="form-group row">
                    <label class="col-lg-5" for="orng">Outfield Range</label>
                    <input class="form-control col-lg-3" type="number" name="orng" [(ngModel)]="this.skills[6]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="oerr">Outfield Error</label>
                    <input class="form-control col-lg-3" type="number" name="oerr" [(ngModel)]="this.skills[7]"/>
                </div>
                <div class="form-group row">
                    <label class="col-lg-5" for="oarm">Outfield Arm</label>
                    <input class="form-control col-lg-3" type="number" name="oarm" [(ngModel)]="this.skills[8]"/>
                </div>
                <div class="row" *ngIf="this.errorRange">
                    <div class="col-11 error">Ratings must be within the range of the selected scale!</div>
                </div>
                <div class="row" *ngIf="this.errorInterval">
                    <div class="col-11 error">20-80 ratings must be multiples of 5!</div>
                </div>
                <div class="row" *ngIf="this.errorGroup">
                    <div class="col-11 error">Please fill out at least one group of ratings before submitting!</div>
                </div>
                <div class="form-group row">
                    <div class="col-lg-5"></div>
                    <button id="submit" class="btn btn-ootp" (click)="onSubmit($event)">SUBMIT</button>
                    <button id="clear" class="btn btn-clear" (click)="onClear($event)">CLEAR</button>
                </div>
                <br>
            </form>
        </div>
        <div class="col-md-6">
            <h2>POSITIONAL POTENTIAL</h2>
            <hr>
            <table class="table">
                <tr class="header">
                    <th>Position</th>
                    <th>Rating</th>
                    <th>WAR</th>
                </tr>
                <tbody>
                    <tr *ngFor="let pos of this.positions; index as i; first as isFirst">
                        <td>{{this.positions[i]}}</td>
                        <td style="color:{{this.colors[i]}}">{{this.ratings[i]}}</td>
                        <td>{{this.wars[i]}}</td>
                    </tr>
                </tbody>
            </table>
            <br><h3>NOTES</h3>
            <hr style="margin-top: 10px; margin-bottom: 10px">
            <p class="notes"><b>Height</b> only affects First Base rating.</p>
            <p class="notes"><b>Lefties</b> will not generate ratings at 2B, 3B, or SS.</p>
            <p class="notes"><b>Catcher Ability</b> and <b>Catcher Arm</b> only affect Catcher rating.</p>
            <p class="notes"><b>Infield Range</b>, <b>Infield Error</b>, <b>Infield Arm</b>, and <b>Turn DP</b> only affect infield ratings (1B, 2B, 3B, SS).</p>
            <p class="notes"><b>Outfield Range</b>, <b>Outfield Error</b>, and <b>Outfield Arm</b> only affect outfield ratings (LF, CF, RF).</p>
            <p class="notes"><b>Rating</b> is the player's maximum possible defensive rating for the given position.</p>
            <p class="notes"><b>WAR</b> is the player's <i>estimated</i> full-season defensive WAR for the given position.</p>
        </div>
    </div>
</div>
